name: DownloadNovel

on:
  workflow_dispatch:
    inputs:
      NovelName:
        description: '小说名称'
        required: true
        default: '我的'
        type: string
      NovelSource:
        description: '小说来源'
        required: true
        default: '147xs'
        type: choice
        options:
        - '147xs'

jobs:
  search_download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./release/novel_download
      - run: RUST_LOG=info ./release/novel_download ${{inputs.NovelName}}
      - name: upload text
        uses: actions/upload-artifact@v3.1.1
        with:
          # Artifact name
          name: novel  #tional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./release/*.txt
          # The desired behavior if no files are found using the provided path.
          retention-days: 30 # optional
