name: Rust

on:
  push
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: rustup target add x86_64-unknown-linux-musl && sudo apt-get install pkg-config libssl-dev && wget https://musl.cc/x86_64-linux-musl-cross.tgz && tar -xzvf x86_64-linux-musl-cross.tgz && pwd && tree . 
    - name: Run Build Release
      run:  pwd && tree . && export PATH=$PATH:/home/runner/work/novel_download/novel_download/x86_64-linux-musl-cross/bin && TARGET_CC=x86_64-linux-musl-gcc cargo build --release --target=x86_64-unknown-linux-musl
    - name: upload artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        # Artifact name
        name: novel_download  #tional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/x86_64-unknown-linux-musl/release/novel_download
        # The desired behavior if no files are found using the provided path.
        retention-days: 30 # optional
    - run: /bin/cp -f ./target/x86_64-unknown-linux-musl/release/novel_download ./release/
    - name: Commit files
      run: |
        git add ./release/novel_download
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "自动提交二进制程序"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}